//
// Created by nikitabakunovich on 20.03.24.
//

#ifndef SAVINICH_BAKUNOVICH_OSISP_PRJ_2024_LOGIC_H
#define SAVINICH_BAKUNOVICH_OSISP_PRJ_2024_LOGIC_H


#endif //SAVINICH_BAKUNOVICH_OSISP_PRJ_2024_LOGIC_H
